Font Change
MSB-s-Projects/Git-scm-Clone pull request #4
Opened 2023-01-30 14:47 UTC by Sehaj-kahlon

## Description
Added different font 

## Issue Resolved
 Fixes #1.

## Screenshots 

![image](https://user-images.githubusercontent.com/114355575/215509349-6bb9d187-0288-43d9-9c8e-14e4f498b5eb.png)

2023-01-30 16:49 UTC, Manobal-Singh-Bagady approved these changes
The Changes Looks Good to me. Good Work, @Sehaj-kahlon 👍, Please make a comment Comment the issue thread #1 so that I can assign the issue to you.

2023-01-30 17:12 UTC, Manobal-Singh-Bagady requested changes
Please update the version to the latest version too. Sorry that was not mentioned in the issue.

2023-01-30 17:31 UTC, Sehaj-kahlon commented
do i have to update the release date too??

2023-01-31 07:29 UTC, Manobal-Singh-Bagady commented
> do i have to update the release date too??

Yeah sure you can do that too but please first comment on #1 so that i can assign you this issue.

2023-01-31 09:03 UTC, Manobal-Singh-Bagady commented
Alright I have assigned the issue to you, please complete the requested changes and i will merge the pull request 👍

2023-01-31 11:07 UTC, Sehaj-kahlon commented
![image](https://user-images.githubusercontent.com/114355575/215743667-73cbda6b-9778-4f9c-a395-f5aa11707ed2.png)

## updated the version and release date

2023-01-31 11:21 UTC, Manobal-Singh-Bagady approved these changes
Ok, Everything Looks Good to me.  Good Work, @Sehaj-kahlon. I am merging the Pull Request.

2023-01-31 11:21 UTC, Manobal-Singh-Bagady commented on index.html
> +            <span class="version">2.39.0</span>
Please update the version from 2.39.0 to the current latest version.

2023-01-31 11:22 UTC, merged